---
version: "2.0"

services:
  web:
    image: moonbys/moonubu:j16
    tty: true
    command:
      - "/usr/bin/sleep"
    args:
      - "infinity"
    stdin_open: true
    restart: unless-stopped
    expose:
      - port: 25565
        proto: tcp
        accept:
          - yourdomain.com
        to:
          - global: true
      - port: 25575
        proto: tcp
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1.5
        memory:
          size: 6Gi
        storage:
          size: 5Gi
  placement:
    chooseyourlocation:
        pricing:
          web:
            denom: uakt
            amount: 1000

deployment:
  web:
    chooseyourlocation:
      profile: web
      count: 1
