---
version: "2.0"

services:
  web:
    image: moonbys/minecraft:master
    expose:
      - port: 25565
        proto: tcp
        to:
          - global: true
      - port: 25575
        proto: tcp
        to:
          - global: true   
    env:
      - FORCE_REDOWNLOAD=true
      - EULA=TRUE
      - VERSION=LATEST
      - SERVER_NAME=YourServerName
      - MEMORY=5G
      - MAX_PLAYERS=12
      - ENABLE_RCON=true
      - RCON_PASSWORD=yoursupersecretpassword
      - JVM_OPTS=-Xmn1G -Xmx5G
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 2
        memory:
          size: 6Gi
        storage:
          size: 5G
  placement:
    dcloud:
      attributes:
        datacenter: equinix-metal-ewr1
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
